name: "Deploy Core"

env:
    FOUNDRY_PROFILE: "lite"
    # API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
    # API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
    # API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
    # MNEMONIC: ${{ secrets.MNEMONIC }}

on:
    workflow_dispatch:
        inputs:
            governor:
                default: "0x516ABfc478658666950CD371685A4Fc6ce73C6C7"
                description: "Initial Governor"
                required: false
            chain:
                default: "sepolia"
                description: "Chain name as defined in foundry.toml"
                required: false
jobs:
    deploy-core:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                submodules: "recursive"

            - name: "Install Foundry"
              uses: "foundry-rs/foundry-toolchain@v1"

            - name: "Deploy the Receivable and Globals contract of Isle Finance"
              run: >-
                forge script scripts/DeployCore.s.sol
                --broadcast
                --rpc-url "${{ inputs.chain }}"
                --sig "run(address)"
                --verify
                "${{ inputs.governor }}"
                -vvvv

            - name: "Add workflow summary"
              run: |
                echo "## Result" >> $GITHUB_STEP_SUMMARY
                echo "✅ Done" >> $GITHUB_STEP_SUMMARY


