name: "Update Accounting"

env:
    FOUNDRY_PROFILE: "optimized"
    MNEMONIC: ${{ secrets.MNEMONIC }}
    API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
    API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
    API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}

on:
    workflow_dispatch:
    schedule:
        - cron: "00 10 * * *" # Scheduled trigger at 6 PM GMT+8

jobs:
    update_accounting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - poolAddressesProvider: "0x51b235a5511e7c25a3f610081f096101cca72f99"
                      chain: "https://devnet-rpc.plumenetwork.xyz"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                  submodules: "recursive"

            - name: "Execution PoolAddressesProvider & chain"
              run: |
                  echo "POOL_ADDRESSES_PROVIDER=${{ matrix.poolAddressesProvider }}"
                  echo "CHAIN=${{ matrix.chain }}"

            - name: "Install Foundry"
              uses: "foundry-rs/foundry-toolchain@v1"

            - name: "Update the accounting of the specified pool"
              run: >-
                  forge script scripts/updateAccounting.s.sol --broadcast --rpc-url "${{ matrix.chain }}" --sig
                  "run(address)" "${{ matrix.poolAddressesProvider }}" -vvvv

            - name: "Add workflow summary"
              run: |
                  echo "## Result" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Done" >> $GITHUB_STEP_SUMMARY
